name: Ionic CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ✅ FIXED NODE VERSION
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - run: npm install -g @ionic/cli
      - run: ionic build

      - run: npx cap sync android

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: cd android && chmod +x gradlew && ./gradlew assembleDebug